"""u-3

Revision ID: 0d7fc111e020
Revises: 2b5a9edc2d5d
Create Date: 2025-05-03 23:26:25.978229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d7fc111e020'
down_revision: Union[str, None] = '2b5a9edc2d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
