"""creat table post

Revision ID: 4bec57366fb0
Revises: 13b03d94156d
Create Date: 2025-05-03 21:43:01.659821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4bec57366fb0'
down_revision: Union[str, None] = '13b03d94156d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(),nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('people', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('people', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('ix_people_id', table_name='people')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_people_id', 'people', ['id'], unique=False)
    op.alter_column('people', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('people', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_table('post')
    # ### end Alembic commands ###
