"""tabpe person inset email 

Revision ID: c78a2d3cfd77
Revises: d0b4bb317ecc
Create Date: 2025-05-05 13:21:30.215429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78a2d3cfd77'
down_revision: Union[str, None] = 'd0b4bb317ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'email')
    # ### end Alembic commands ###
